### ISSUE TITLE
Make doesn't work on OSX and python 3.7

### ISSUE THREAD

**Issue by PaulRBerg** [omisego/plasma-mvp#166]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

Cannot build the source code, although I made sure that:

- I have `leveldb` correctly installed (via homebrew) and there's a link in `/usr/local/include`
- I ran `xcode-select --install` and when I run `gcc -v` I correctly see `/usr/local/include` mentioned there

## Expected Behavior

`make` should work.

## Steps to Reproduce

This is perhaps a problem specific to OSX.

1. git clone git@github.com:omisego/plasma-mvp.git
2. virtualenv env -p python3
3. source ./env/bin/activate
4. make

Full output of error:
```
Searching for plyvel==1.0.4
Reading https://pypi.org/simple/plyvel/
Downloading https://files.pythonhosted.org/packages/e0/7b/9302e33972c4af861f5a425cb37468b4dbb17d7a4d282a657bfdb240055e/plyvel-1.0.4.tar.gz#sha256=134e78519403a6f71f1e66df945763413c48d0f6dec02e1a61f55adf0f83106d
Best match: plyvel 1.0.4
Processing plyvel-1.0.4.tar.gz
Writing /var/folders/_x/nsr657154_s4z371xj0fvg8m0000gq/T/easy_install-kg9t4l73/plyvel-1.0.4/setup.cfg
Running plyvel-1.0.4/setup.py -q bdist_egg --dist-dir /var/folders/_x/nsr657154_s4z371xj0fvg8m0000gq/T/easy_install-kg9t4l73/plyvel-1.0.4/egg-dist-tmp-_e82k3tc
warning: no files found matching 'plyvel/*.pxi'
plyvel/_plyvel.cpp:547:10: fatal error: 'leveldb/db.h' file not found
#include "leveldb/db.h"
         ^~~~~~~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
make: *** [Makefile:2: init] Error 1
```

## System Specs

- operating system: osx high sierra 10.13.5
- python version: 3.7
- virtualenv: 16.0.0
- pyetherem version: 2.3.0
- environment (output of running `pip freeze`):
```
click==6.7
flake8==3.5.0
plasma==0.0.0
py-solc==3.1.0
pytest==3.7.1
rlp==0.6.0
```

**Comment by PaulRBerg** [comment]
I managed to get it working:

## Without `virtualenv`
I had to reinstall `openssl` and follow the instructions from here: https://github.com/ethereum/pyethapp/issues/209. Afterwards, the install ran smoothly.

## With `virtualenv`
I switched to `pyenv` and `pyend-virtualenv` and, after fiddling with the tools for a while, I managed to run `make` successfully inside the environment. Of course, tests don't work but I see that there are already PRs for that.

Did this happen just to me? I might update the README to add some warnings for OSX.

Considering the latest developments of Plasma (Cash, Debit et al), is OmiseGo even working on the mvp at all?

**Comment by kfichter** [comment]
Weird. I haven't seen this issue yet. I guess if it's working now I'll close (?).

**Comment by PaulRBerg** [comment]
Yup! I just wanted to make sure it was something with my machine. Thanks!
